swagger: "2.0"
info:
  title: API's(swagger) For Admin-Panel
  description: This is for admin panel made by me
  version: 1.0
  contact:
    email: prabhatvverma@gmail.com
  liscence: 
    name: Apche 2.0
    url: "http://apache.org/"
  servers:
    -url: "http://localhost:3000/"
    discription: This is my local server
    -url: "http://websitepath.com/"
    discription: This is my company server

schemes: [http,https]

paths: 
#login url
  /login:
    get:
      summary: This route will return your login page
      description: It will load login page you can login now usin crenditials here we have email password and a route is defined on login button 
      responses:
        200: 
          description: Success
          schema: 
            type: string
        400:
          description: User Error
        500:
          description: Internal Server Error
# Register url
  /register:
    get:
      summary: This route will return you register page 
      description: It will load register page have all the fields for a user to register with admin panel
      responses:
        200:
          description: Success
          schema:
            type: string

        